###
GET http://localhost:8080/albums/1

###
POST http://localhost:8080/albums/addAlbum
Content-Type: application/json

{
  "title": "20 top music",
  "image": "/images/top_20.jpg",
  "recordLabel": "A Label",
  "comments": [],
  "ratings": 2,
  "songs": []
}