###
GET http://localhost:8080/albums/1


###
GET http://localhost:8080/songs/4

###
POST http://localhost:8080/albums/addAlbum
Content-Type: application/json

{
  "title": "20 top music",
  "image": "/images/top_20.jpg",
  "recordLabel": "A Label",
  "comments": [
    
  ],
  "ratings": 2,
  "songs": []
}



###
POST http://localhost:8080/albums/2/addSong
Content-Type: application/json

{
  "id": 6,
  "title": "badSong",
  "link": "/badSong/link",
  "duration": 10,
  "comments": [],
  "ratings": 1
}

###
DELETE  http://localhost:8080/albums/1

### add comment for album
POST http://localhost:8080/albums/1/updateAlbumComment

I don't like this album.

###
GET http://localhost:8080/albums

